# Generated by Django 4.1.1 on 2023-10-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukraine_swu', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='header',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
