# Generated by Django 4.2.5 on 2023-11-13 12:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ukraine_swu', '0009_entry_budget_entry_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='full_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
