# Generated by Django 4.2.5 on 2023-11-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ukraine_swu', '0012_entry_rich_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='full_text',
        ),
    ]
